services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: hirenext_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: hirenext
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirenext_dev
    ports:
      - "5432:5432"
    volumes:
      - ./apps/api/.docker/pgdata:/var/lib/postgresql/data
