services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    restart: unless-stopped
    depends_on:
      - database
      - redis
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -p 5432"]
      interval: 5s
      retries: 5

  database:
    image: postgres:17-alpine
    container_name: hirenxt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hirenxt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirenxt
    ports:
      - "5432:5432"
    volumes:
      - ./apps/api/.docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -p 5432 -U hirenxt"]
      interval: 5s
      retries: 5

  redis:
    image: redis:alpine3.22
    container_name: hirenxt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./apps/api/.docker/redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


